### ISSUE TITLE
Page with example

### ISSUE THREAD

**Issue by ghost** [SoorajSNBlaze333/tooltip-sequence#3]
I think this project would definitly benefit from a quick and simple example page.
maybe using github static pages.

Cheers.

**Comment by SoorajSNBlaze333** [comment]
Hey there @dioio-io. Sorry about that, I forgot to include it in the README. Here is the demo page [https://tooltip-sequence.netlify.app/](https://tooltip-sequence.netlify.app/). Thanks for the heads up :)
